version: '2'
services:
    quyenbeo_admin-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        command: mongos --configdb quyenbeo_admin-mongodb-config
    quyenbeo_admin-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    quyenbeo_admin-mongodb-config:
        image: mongo:3.4.8
        container_name: quyenbeo_admin-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
