version: '2'
services:
    quyenbeo_admin-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/quyenbeo_admin/mongodb/:/data/db/
